# Generated by Django 3.0.2 on 2020-02-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetRef',
            fields=[
                ('tweet_text', models.CharField(max_length=280)),
                ('tweet_date', models.DateField()),
                ('tweet_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
